stages:
  train:
    deps:
      - data
      - eds_pseudo
      - scripts/train.py
      - configs/config.cfg
    cmd:
      - python scripts/train.py --config configs/config.cfg
      - python scripts/evaluate.py --config configs/config.cfg
      - python scripts/package.py
    metrics:
      - artifacts/test_metrics.json:
          cache: false
    outs:
      - artifacts/test_metrics_per_doc.jsonl:
          cache: false
