stages:
  train:
    deps:
      - data
      - eds_pseudonymisation
      - scripts/train.py
    params:
      - configs/config.cfg:
    cmd:
      - python scripts/train.py --config configs/config.cfg
      - python scripts/evaluate.py --config configs/config.cfg
    metrics:
      - artifacts/test_metrics.json:
          cache: false
      - artifacts/test_metrics_per_doc.jsonl:
          cache: false
