from collections import defaultdict

from spacy.tokens import Span

from eds_pseudo.scorer import PseudoScorer


def test_scorer(nlp):
    scorer = PseudoScorer(
        ml_spans="pseudo-ml",
        rb_spans="pseudo-rb",
        hybrid_spans="pseudo-hybrid",
        main_mode="rb",
        compute_speed=True,
    )
    text = "Dr. Juan a pour mail don juan@caramail.fr vit a grigny, tel 0607080910."
    doc = nlp.make_doc(text)
    doc.spans["pseudo-rb"] = [
        Span(doc, 1, 2, "NOM"),
        Span(doc, 6, 11, "MAIL"),
        Span(doc, 13, 14, "CITY"),
        Span(doc, 16, 17, "MAIL"),  # not a mail but to test the scorer
    ]
    main_scores = scorer(nlp, [doc, nlp.make_doc("")])

    grouped_metrics = defaultdict(lambda: {})
    for metric in main_scores:
        parts = [key.strip() for key in metric["name"].split("/")]
        value = metric["value"]
        current = grouped_metrics
        for key in parts[:-1]:
            current = current.setdefault(key, {})
        current[parts[-1]] = value

    assert set(grouped_metrics["Token Scores"]["micro"].keys()) == {
        "F1",
        "Redact Full",
        "Precision",
        "Recall",
        "Redact",
    }
    assert (
        grouped_metrics["Speed"]["Words per second"]["Value"] > 0
        and grouped_metrics["Speed"]["Docs per second"]["Value"] > 0
    )

    doc_scores = scorer(nlp, [doc, nlp.make_doc("")], per_doc=True)[1]
    assert doc_scores == [
        {
            "label": "micro",
            "matching": "exact",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 3,
            "support": 4,
            "tp": 2,
        },
        {
            "label": "NOM",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 1,
            "tp": 1,
        },
        {
            "label": "MAIL",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 2,
            "tp": 1,
        },
        {
            "label": "TEL",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "CITY",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 1,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "exact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 3,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "NOM",
            "matching": "exact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "MAIL",
            "matching": "exact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "TEL",
            "matching": "exact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 7,
            "support": 8,
            "tp": 6,
        },
        {
            "label": "NOM",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 1,
            "tp": 1,
        },
        {
            "label": "MAIL",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 5,
            "support": 6,
            "tp": 5,
        },
        {
            "label": "TEL",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "CITY",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 1,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 7,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "NOM",
            "matching": "token",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "MAIL",
            "matching": "token",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 5,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "TEL",
            "matching": "token",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 1,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 8,
            "tp": 7,
        },
        {
            "label": "NOM",
            "matching": "redact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 1,
            "tp": 1,
        },
        {
            "label": "MAIL",
            "matching": "redact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 6,
            "tp": 6,
        },
        {
            "label": "CITY",
            "matching": "redact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 1,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "exact",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "exact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "exact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "token",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "positives": 0,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "ml",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "rb",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 0,
            "tp": 0,
        },
        {
            "label": "micro",
            "matching": "redact",
            "mode": "hybrid",
            "note_class_source_value": "unknown",
            "note_id": None,
            "support": 0,
            "tp": 0,
        },
    ]
