# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  PyPI:
    name: Build wheels and push to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Build wheels
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set PY variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config cache-dir ~/.cache/poetry

      - uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key: poetry|${{ env.PY }}|${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install

      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Build documentation
        run: |
          git fetch origin gh-pages
          poetry run mike deploy --push --no-redirect --update-aliases $GITHUB_REF_NAME latest
